version: "3.7"

services:
  webserver-my:
    image: nginx:alpine
    container_name: webserver-my
    working_dir: /app
    volumes:
      - ../../project/app/backend:/app
      - ../webserver/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app-my-network

  app-backend-my:
    build: app/backend
    container_name: app-backend-my
    volumes:
      - ../../project/app/backend:/app
      - backend-user-worker:/home/worker
    networks:
      - app-my-network

  app-frontend-my:
    build: app/frontend
    container_name: app-frontend-my
    volumes:
      - ../../project/app/frontend:/app
      - frontend-bash-dir:/home/worker
    networks:
      - app-my-network

  db-my:
    image: mysql:8.0
    container_name: db-my
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - db-my-data:/var/lib/mysql
    networks:
      - app-my-network

volumes:
  backend-user-worker:
  frontend-bash-dir:
  db-my-data:

networks:
  app-my-network: