version: "3.7"

services:
  my-web:
    image: nginx:alpine
    container_name: my-web
    working_dir: /app
    volumes:
      - ../../project/app/backend:/app
      - ../webserver/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - mynet

  my-api:
    build: app/backend
    container_name: my-api
    volumes:
      - ../../project/app/backend:/app
      - my-api-user-worker:/home/worker
    networks:
      - mynet

  my-app:
    build: app/frontend
    container_name: my-app
    volumes:
      - ../../project/app/frontend:/app
      - my-app-user-worker:/home/worker
    networks:
      - mynet

  my-db:
    image: mysql:8.0
    container_name: my-db
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - my-db-data:/var/lib/mysql
    networks:
      - mynet

volumes:
  my-api-user-worker:
  my-app-user-worker:
  my-db-data:

networks:
  mynet: