parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  My\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  My\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  my.model_builder.task:
    class: ModelBuilder\Builder
    factory: [ '@ModelBuilder\Manager\DefaultBuildManager', 'createBuilder' ]
    arguments:
      - My\Model\Data\Task

  My\Controller\DefaultController:
    tags: [ controller.service_arguments ]
    bind:
      $taskBuilder: '@my.model_builder.task'

  My\Listener\ViewListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view }
